name: Package macOS application

on: push

jobs:
  package-macos:
    name: Package macOS application
    runs-on: macos-latest

    steps:
      - name: Download MacPorts
        # fixme: add caching
        run: |
          curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.6.4-11.0-BigSur.pkg

      - name: Install MacPorts
        run: |
          sudo /usr/sbin/installer -pkg MacPorts-2.6.4-11.0-BigSur.pkg -target /

      - name: Install dependencies
        run: |
          port version
          sudo port install skrooge
