name: Package macOS application

on: push

jobs:
  package-macos:
    name: Package macOS application
    runs-on: macos-latest

    steps:
      - name: Add KDE5 homebrew tap
        run: |
          brew list --formula
          brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
          "$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
          
      - name: Install skrooge dependencies
        run: |
          brew install boost libofx qca sqlcipher sqlite3
          brew install --HEAD grantlee
          brew install kf5-kactivities kf5-kcoreaddons kf5-kdeclarative kf5-kdelibs4support kf5-kdewebkit kf5-kiconthemes kf5-kirigami2 kf5-knewstuff kf5-knotifyconfig kf5-kparts kf5-kross kf5-krunner kf5-kwallet kf5-kxmlgui kf5-plasma-framework
          
      - name: Checkout source code
        run: git clone --depth=1 https://invent.kde.org/office/skrooge.git

      - name: Build skrooge
        run: |
          export LDFLAGS="-L/usr/local/opt/qt/lib"
          export CPPFLAGS="-I/usr/local/opt/qt/include"
          export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
          cmake -Bbuild -Hskrooge -DCMAKE_INSTALL_PREFIX=$(pwd)/install
          make -C build getpo
          make -C build
          make -C build install
          
