name: Package macOS application

on: push

jobs:
  package-macos:
    name: Package macOS application
    runs-on: macos-latest

    steps:
      - name: Add KDE5 homebrew tap
        run: |
          brew list
          brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
          "$(brew --repo kde-mac/kde)/tools/do-caveats.sh"
          
      - name: Install skrooge dependencies
        run: |
          "$(brew --repo kde-mac/kde)/tools/install.sh"
          brew install qca libofx
          
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          repository: https://invent.kde.org/office/skrooge.git

      - name: Build skrooge
        run: |
          cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=$(pwd)/install
          make -C build getpo
          make -C build
          make -C build install
          
